ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUGs5w+BGQXTTbvXikERBHnZfLMDymrWd3NVFlaWCloAPvC/1bJR1qnSZHGZU21kkz1zHoZwHvwU1OkICFmDugkORO5Jc8S/E4O6qqTPBlxNz/6dxigy3rq0XkvDo/pA6dpOlf3NwVrdpNP434iATI7coxtMk430wIMOxYuaWDuYMZsefSZqWS+5PIfzR/HhmQ6yxTz4q5ybthfEufI7OaucO5ux+awUA0+vMa2sjrZYDBBqt+cb+FrOe47syriScTqJy9hBN6+fkBdIo1v/27z0HyPqYf6W4cmvJbrP//+7Qx/SnA0xEL2v2rg94K+9edcXYGWMh5PJ5KWPMXOecC7XMwoXBF06WpPo315KP+/WoYklHWPOEwTNcNcY5xKJTmbo8dTOaPG8+sMNm3w7tLmmNNJ+sBBrEa2/LH88ZghEe1sshN9kOe91xmEmkiV42cGyOWsyIBpcvpmQvBjkRumVxec4u3e3jeuO5gUOt8zVGAaW0AYCtf5e9u13m2SVE= ben@myers.rocks
- github:draconis2941

hostname: stack1
